project:
  type: website
  output-dir: docs

website:
  title: "Le site de Duc Tung VU"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/d-tvu
      - icon: mailbox
        href: mailto:ductungvu0711@gmail.com
format:
  html:
    theme: cosmo
    css: styles.css



